[package]
name = "minimal-id"
version = "0.1.0"
authors = ["Russell Hay <me@russellhay.com>"]
edition = "2018"
description = "A library that implements generating short, unique ids with minimal collisions and good locality"

[dependencies]
byteorder = "~1"
data-encoding = "~2"
rand = "~0"
